api_platform:
    mapping:
        paths:
        - '%kernel.project_dir%/src/Domain/Entity'
    title: Plataforma de Prueba acceso
    description: Esta es la prueba para el acceso
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
